language: node_js
node_js:
- stable
cache:
  directories: 
env:
  global:
  - secure: U7u3upWhxglEVqq1TrYmSbhhEO3OzdqsM67PGsFabgiqvFg8k1rGne+LIV6EbdRwBgbtcBG+OeZKqyp2Ai0VW5ZhBjc64MZDiM4mMxUlVImQZMwOeAfOO5H77HN4sm8zrPww7sXxRGS2HPXQhQ0ARRVaT93LijAylXd3YUBDF8cveIIx/F1xMZ/T+KLEdWd4roM4lmYwP+COVcEkFoSYx2CumpXxWJEqRT79pz+iUvVJ511JrIhXJe56QvsmtLl0cppgJMGoNylrxK1EgNfXz6qsgZI1N+jyGaUHtXqZr/ZnrS0K5bqOPVlqDCzvjrCGyJ7FZw9ujEXyTF0/uqumNxgSd0bKuqjXBtyDpzPM8IBxKgu94UE5fuH4RaDoXZD6QCU3LKVLdoJJ3YdcRB0Okc6Vh3I0MJNfu64gkLTSrGvA18Nti6WgMaHlz2QiBAQmcziMik2AXiHHCbuaNNf8o+gnCYYpxx0CvT9bLqUtbejiLe1RVdqNtAZ0dXzh5OAoWQLlQJIbcIr3jYbxkWaR7zm5d9tOQSXKxrmEZcV3jMFohm/0oeNnYop+v98CNXb1A3l7cQGyeS0pp2asAH4o1r9mdL8HAQlob8kmnbXf/HvJh/VczQYXxeED90zGrzUByDn8O64iW9KcxVNpoQr005hOovq3KW+I6ddP0ZYB1XM=
script: "./deploy.sh"
