language: node_js

node_js:
  - "stable"

cache:
  directories:
  # - node_modules

env:
  global:
    - secure: "hVfK924YErndfLUcLq04IwzvKVJJgiV1tdCPgGDJz7wzBFj3YKI+BE/+8TUIXAgRDNl0hslYdyPMNbGOur2w91sksGy/qfk1vZjoe1S43n1f5/nYcIOkQjLSUU/UfMxiZ8UHnXg3wGdIYwb92/526ylykb8wlUFdUmRkZcyArvRFtMrpgXT4stzj5fFyqcotkg1Kdyk7896ttCsRyxesUZ8QqNrLJmiR0D0kOM6XUIyzK9rgAJAety/kuJCCsBMNHIjEw8zNALnpOIG0FyI7BRWnz1VXKwt5dAJvl7fMgwZ4X7uaEFXK8AshdpgRhZcSwemXvD4fCfb4SuCmW6pr9fqEQNiavURokcyKIyEJnhqf0mvOuMaNuRNTI0QSguMfC09YLEqrkaIvhgvAH9UiLn29zq0pyGd917Q6WrjMjHcrbdW5ZzSE57cKhbByPCbbLL+aKPc4oAGL8vJ6SacZB+8IOM5+ey8VIttkdRfzCWE2q4MJeDLrQc8AQoewZVejcK0vrGk3S1I1jYH/oeas9bwSOpzML879N6/X0FyWRaKYRKuogdec7HXWfzLAIvSwQ1mIi0hVF4jaV7lsZokXXJf9eXpojzZLc6dYYiHQ/fAuf1KZLsngNKpuSu1mBMxJZ9ZzBt1n+q0vPRgCksSJa/oA66ZIJEKybVsyCF25Elc="

script:
  ./deploy.sh
  # - npm test
  # - npm run build